### ISSUE TITLE
Definicion y conceptos mas importantes de Entidad - Relacion

### ISSUE THREAD

**Issue by CynGarcia25** [CynGarcia25/RecoleccionDeInformacion#4]
tema entidad - relacion

**Comment by PauMoratalla0301** [comment]
Definicion y conceptos de Entidad-Relacion
                     (Paula Moratalla)
-	El modelo entidad relación es una herramienta para el modelo de datos, la cual facilita la representacion de entidades de una base de datos.
-	El modelo entidad relacion tiene tres componentes:

*Entidades: Representa una “cosa”, “objeto” o “concepto” del mundo real con existencia independiente.

*Atributos: Son las caracteristicas que definen o identifican una entidad.

*Relaciones: Consiste en una relacion o conjunto, de relaciones de la misma naturaleza. 
Se suele desarrollar en dos fases:
-Se elabora el diagrama entidad-relacion
-Se completa el diagrama con una listas de atributos y una descripcion de otras restricciones que no se pueden reflejar en el diagrama.

Correspondencia de Cardinalidades:
-Dado un conjunto de relaciones en el que participan 2 o mas entidades. 
- Dado un conjunto de relaciones binariasy los conjuntos de entidades A y B, las cardinalidades pueden ser:
*Uno a uno: (1:1)
*Uno a varios: (1:N)
*Varios a uno: (N:1)
*Varios a varios: (N:M)


Claves
Es un subconjunto del conjunto de atributos comunes en una colección de entidades, que permite identificar inequívocamente cada una de las entidades pertenecientes a dicha colección. Asimismo, permiten distinguir entre sí las relaciones de un conjunto de relaciones.
Dentro de los conjuntos de entidades existen los siguientes tipos de claves:
Superclave: Es un subconjunto de atributos que permite distinguir unívocamente cada una de las entidades de un conjunto de entidades. Si se añade un atributo al anterior subconjunto, el resultado seguirá siendo una superclave.
•	Clave candidata: Se trata de superclave mínima, es decir, cualquier subconjunto de atributos de la misma no puede ser una superclave.
•	Clave primaria: Es una clave candidata, elegida por el diseñador de la base de datos, para identificar unívocamente las entidades en un conjunto de entidades.
Los valores de los atributos de una clave, no pueden ser todos iguales para dos o más instancias.
Para poder distinguir unívocamente las relaciones en un conjunto de relaciones R, se deben considerar dos casos:
•	R NO tiene atributos asociados: En este caso, se usa como clave primaria de R la unión de las claves primarias de todos los conjuntos de entidades participantes.
•	R tiene atributos asociados: En este caso, se usa como clave primaria de R la unión de los atributos asociados y las claves primarias de todos los conjuntos de entidades participantes.
Si el conjunto de relaciones, R, sobre las que se pretende determinar la clave primaria está compuesto de relaciones binarias, con los conjuntos de entidades participantes A y B, se consideran los siguientes casos, según sus cardinalidades:
•	R es de muchos a uno de A a B entonces solo se toma la clave primaria de A, como clave primaria de R.
•	R es de uno a muchos de A a B entonces se toma solo la clave primaria de B, como clave primaria de R.
•	R es de uno a uno de A a B entonces se toma cualquiera de las dos claves primarias, como clave primaria de R, y se crea una restricción de no repetición para la otra clave.
•	R es de muchos a muchos de A a B entonces se toma la unión de los atributos que conforman las claves primarias de A y de B, como clave primaria de R.
