### ISSUE TITLE
Normalizacion

### ISSUE THREAD

**Issue by CynGarcia25** [CynGarcia25/RecoleccionDeInformacion#5]
las 4 formas de normalizacion

**Comment by rominarg** [comment]
La normalización de bases de datos es un proceso que consiste en designar y aplicar una serie de reglas a las relaciones obtenidas tras el paso del modelo entidad-relación al modelo relacional con objeto de minimizar la redundancia de datos, facilitando su gestión posterior.

Objetivo
Las bases de datos relacionales se normalizan para:

Minimizar la redundancia de los datos.
Disminuir problemas de actualización de los datos en las tablas.
Proteger la integridad de datos.
En el modelo relacional es frecuente llamar «tabla» a una relación; para que una tabla sea considerada como una relación tiene que cumplir con algunas restricciones:

Cada tabla debe tener su nombre único.
No puede haber dos filas iguales. No se permiten los duplicados.
Todos los datos en una columna deben ser del mismo tipo.
