### ISSUE TITLE
conceptos ejercicio profesional

### ISSUE THREAD

**Issue by CynGarcia25** [CynGarcia25/RecoleccionDeInformacion#7]
conceptos generales sobre la introduccion de la materia

**Comment by wholie** [comment]
conceptos generales sobre la introduccion de la materia
El espacio “Ejercicio Profesional” que procura sentar de modo colaborativo y coordinado, las bases iniciales de la carrera y otorgar al estudiante las directrices principales y líneas de acción para entender y comprender como la actividad se inserta, desarrolla, gestiona y da complejidad al marco de un espacio de entramado de interacción de equipo de trabajo dentro del aula virtual y en un futuro del desarrollo profesional. En este módulo se articula saberes, contenidos y competencias a partir de uno o varios proyectos, y su aprobación acreditan un saber hacer que le permite al estudiante desarrollar una tarea en el ámbito laboral. El propósito central de este módulo es brindar una serie de actividades en las que el profesional puede demostrar, una vez que ha logrado los conocimientos adquiridos sobre su profesión. Involucra un conjunto de competencias específicas de desarrollo dentro del sector profesional de Informática.
Los contenidos mínimos son los siguientes:

•Comunicación asertiva.

• Herramientas para la búsqueda de trabajo en relación de dependencia: confección de Curriculum vitae, presentación a entrevistas, técnicas de oralidad.

•El trabajo como profesional independiente.

•Adaptabilidad y flexibilidad.

•Proactividad e iniciativa.

• Introducción a la gestión de proyectos.

•Trabajo en equipos interdisciplinarios.

•Empatía. Creatividad. Liderazgo. Colaboración.

•Resolución de problemas.

•Toma de decisiones.

•Dinámica de grupos.

Este grupo de saberes acreditaran nuestras habilidades a la hora de desarrollarnos en un entorno de trabajo IT dejando en evidencia que la información del **modulo de ejercicio profesional induce a los desarrolladores del ispc a que puedan entender y tomar en cuenta que tanto los conocimientos teóricos como el desenvolvimiento de habilidades blandas mejorar el trabajo y la fluidez a la hora de enfrentar en cualquier proyecto** (ya sea para una empresa o empleador, así mismo como para poder tener una estructura de trabajo en caso de que se pueda trabajar de forma autónoma) .  son conocimientos que mejorar el nuestro trabajo (conocimientos técnicos) y habilidades blandas.

**Comment by wholie** [comment]
El espacio “Ejercicio Profesional” que procura sentar de modo colaborativo y coordinado, las bases iniciales de la carrera y otorgar al estudiante las directrices principales y líneas de acción para entender y comprender como la actividad se inserta, desarrolla, gestiona y da complejidad al marco de un espacio de entramado de interacción de equipo de trabajo dentro del aula virtual y en un futuro del desarrollo profesional. En este módulo se articula saberes, contenidos y competencias a partir de uno o varios proyectos, y su aprobación acreditan un saber hacer que le permite al estudiante desarrollar una tarea en el ámbito laboral. El propósito central de este módulo es brindar una serie de actividades en las que el profesional puede demostrar, una vez que ha logrado los conocimientos adquiridos sobre su profesión. Involucra un conjunto de competencias específicas de desarrollo dentro del sector profesional de Informática.
Los contenidos mínimos son los siguientes:

•Comunicación asertiva.

• Herramientas para la búsqueda de trabajo en relación de dependencia: confección de Curriculum vitae, presentación a entrevistas, técnicas de oralidad.

•El trabajo como profesional independiente.

•Adaptabilidad y flexibilidad.

•Proactividad e iniciativa.

• Introducción a la gestión de proyectos.

•Trabajo en equipos interdisciplinarios.

•Empatía. Creatividad. Liderazgo. Colaboración.

•Resolución de problemas.

•Toma de decisiones.

•Dinámica de grupos.

Este grupo de saberes acreditaran nuestras habilidades a la hora de desarrollarnos en un entorno de trabajo IT dejando en evidencia que la información del **modulo de ejercicio profesional induce a los desarrolladores del ispc a que puedan entender y tomar en cuenta que tanto los conocimientos teóricos como el desenvolvimiento de habilidades blandas mejorar el trabajo y la fluidez a la hora de enfrentar en cualquier proyecto** (ya sea para una empresa o empleador, así mismo como para poder tener una estructura de trabajo en caso de que se pueda trabajar de forma autónoma) .  son conocimientos que mejorar el nuestro trabajo (conocimientos técnicos) y habilidades blandas.
