### ISSUE TITLE
glosario de Base de Datos

### ISSUE THREAD

**Issue by CynGarcia25** [CynGarcia25/RecoleccionDeInformacion#9]
palabras mas importantes de base de datos

**Comment by Leonardo-Valtorta** [comment]
## 1) ¿Qué es SGBD?
Un sistema gestor de bases de datos o **SGBD** (aunque se suele utilizar más a menudo las siglas **DBMS**
procedentes del inglés, Data Base Management System) es el software que permite a los usuarios
procesar, describir, administrar y recuperar los datos almacenados en una base de datos. 

## 2) Componentes de los Sistemas Gestores de Bases de Datos 

- **Lenguaje de definición de datos (LDD o DDL):** se utiliza para especificar el esquema de la BD, las vistas de los usuarios y las estructuras de almacenamiento. Es el que define el esquema conceptual y el esquema interno. Lo utilizan los diseñadores y los administradores de la BD.

- **Lenguaje de manipulación de datos (LMD o DML):** se utilizan para leer y actualizar los datos de la BD. Es el utilizado por los usuarios para realizar consultas, inserciones, eliminaciones y modificaciones. Los hay procedurales, en los que el usuario será normalmente un programador y especifica las operaciones de acceso a los datos llamando a los procedimientos necesarios. Estos lenguajes acceden a un registro y lo procesan. 

## 3) El Administrador de la Base de Datos DBA
El DBA tiene una gran responsabilidad ya que posee el máximo nivel de privilegios. Será el encargado de crear los usuarios que se conectarán a la BD. En la administración de una BD siempre hay que procurar que haya el menor número de administradores, a ser posible una sola persona.
El objetivo principal de un DBA es:

- Instalar SGBD en el sistema informático.
- Crear las BBDD que se vayan a gestionar.
- Crear y mantener el esquema de la BD.
- Crear y mantener las cuentas de usuario de la BD.
- Arrancar y parar SGBD, y cargar las BBDD con las que se ha de trabajar.
- Colaborar con el administrador del S.O. en las tareas de ubicación, dimensionado y control de los archivos y espacios de disco ocupados por el SGBD.
- Colaborar en las tareas de formación de usuarios.
- Establecer estándares de uso, políticas de acceso y protocolos de trabajo diario para los usuarios de la BD.
- Suministrar la información necesaria sobre la BD.

##  4) Diferencias entre el modelo lógico y el conceptual 
El modelo conceptual es independiente del DBMS que se vaya a utilizar. El lógico depende de un tipo de
SGBD en particular.
El modelo lógico está más cerca del modelo físico, el que utiliza internamente el ordenador.
El modelo conceptual es el más cercano al usuario, el lógico es el encargado de establecer el paso entre el modelo conceptual y el modelo físico del sistema.
**Algunos ejemplos de modelos conceptuales son:**
- Modelo Entidad Relación
- Modelo RM/T
- Modelo UML

**Ejemplos de modelos lógicos son:**
- Modelo relacional
- Modelo Codasyl
- Modelo Jerárquico

## 5) Modelo de bases de datos orientadas a objetos. 
Desde la aparición de la programación orientada a objetos (POO u OOP) se empezó a pensar en bases
de datos adaptadas a estos lenguajes. La programación orientada a objetos permite cohesionar datos y
procedimientos, haciendo que se diseñen estructuras que poseen datos (atributos) en las que se
definen los procedimientos (operaciones) que pueden realizar con los datos.

## 6) Bases de datos objeto-relacionales. 
Tratan de ser un híbrido entre el modelo relacional y el orientado a objetos. El problema de las bases de datos orientadas a objetos es que requieren reinvertir capital y esfuerzos de nuevo para convertir las bases de datos relacionales en bases de datos orientadas a objetos. En las bases de datos objeto
relacionales se intenta conseguir una compatibilidad relacional dando la posibilidad de integrar mejoras de la orientación a objetos.

## 7) Bases de datos NoSQL. 
Están pensadas para grabar los datos de manera veloz para así poder atender a miles y miles de peticiones. Es decir, es el modelo de las bases de datos que se utilizan en los grandes servicios de Internet (como twitter, Facebook, Amazon,…).
La idea es que los datos apenas necesitan validarse y relacionarse y lo importante es la disponibilidad de la propia base de datos. 

## 8) Diseño de bases de datos relacionales
### Etapas de diseño
**Diseño conceptual.**
Su objetivo es definir las entidades y las relaciones entre ellos de forma abstracta, sin centrarse en ningún modelo lógico en concreto.
**Diseño lógico.**
Su objetivo es definir el esquema de la base de datos según el modelo que implementa el SGBD objetivo.
**Diseño físico.**
Su objetivo es definir el esquema físico de la base de datos de forma que se den todas las instrucciones para que un DBA pueda implementar la base de datos sin ninguna ambigüedad. Se considera el rendimiento como un aspecto que no se ha tratado en las etapas anteriores.

## 9) Conceptos
**Entidad:** Es el menor objeto con significado en una instancia.
Por ejemplo, para el diseño de una BD de la secretaría de un centro docente, el alumno con los siguientes datos:
```
 DNI = 01234567Z,
 Nombre y apellidos = Manuel Vázquez Prieto,
 Teléfono = 91-12345678
 Domicilio = Calle del Jazmín 7, 4 Izq.
```
Constituye una entidad. Igual sucede con cada asignatura concreta, cada profesor, etc.

**Atributo:** Es cada uno de los componentes que determinan una entidad.
Cada atributo tiene asociado un dominio: el conjunto de valores que puede tomar.
La entidad del ejemplo anterior viene determinada por los valores de sus atributos DNI, Nombre y Apellidos, Teléfono, Domicilio y COU.
En el enfoque clásico serían los campos de los registros.
• Atributos monovalorados y multivalorados: Los atributos multivalorados son los que pueden contener más de un valor simultáneamente, y monovalorados a los que sólo pueden contener un valor.
Por ejemplo, una persona puede tener varios números de teléfono (casa, trabajo, móvil) y puede que nos interese tenerlos todos. En este caso haremos de teléfono un atributo multivalorado.
• Atributos simples y compuestos: Un atributo es compuesto cuando puede descomponerse en otros componentes o atributos más pequeños, y simple en otro caso.
Por ejemplo, en el caso del domicilio puede que nos interese descomponerlo a su vez en calle, el número y la ciudad por separado.
• Clave: Es un atributo o conjunto de atributos cuyos valores identifican unívocamente cada entidad.
Por ejemplo, DNI es un atributo clave del tipo de entidad Alumnos. Esto significa que los valores de la clave no se pueden repetir en el conjunto de entidades. En el ejemplo anterior ningún DNI se debería repetir en una instancia del tipo de entidad Alumnos.
